project:
  type: website
  output-dir: _site

website:
  title: "jax-mppi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Theory"
        href: src/theory.qmd
      - text: "Dynamics"
        href: src/dynamics.qmd
      - text: "I-MPPI"
        href: src/i_mppi.qmd
      - text: "Autotuning"
        href: src/autotuning.qmd
      - text: "Plans"
        href: plan/index.md
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Theory"
        contents:
          - src/theory.qmd
          - src/dynamics.qmd
      - section: "Algorithms"
        contents:
          - src/i_mppi.qmd
          - src/autotuning.qmd
      - section: "Examples"
        contents:
          - examples/pendulum.md
      - section: "Development"
        contents:
          - testing.md
          - releasing.md

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
